apiVersion: v1
kind: Service
metadata:
  name: sb-docker
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: sb-docker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-docker 
  labels:
    app: sb-docker 
    type: backend
    frame: spring
spec:
  selector:
    matchLabels:
      app: sb-docker 
  replicas: 3
  template:
    metadata:
      labels:
        app: sb-docker 
        frame: spring
    spec:
      containers:
      - name: sb-docker
        image: andriim88/spring-docker-test-1:0.0.9
        ports:
        - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: DB_NAME
          value: "postgres"
        - name: DB_URL
          value: "some_url"
