apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  labels:
    app.name: busybox
    app.type: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      args:
        - sleep
        - "1000"
